In [ ]:
#Initialize an empty array with size 2X2.
import numpy as np

arr = np.empty((2, 2),dtype = int)
print(arr)

[[118431646         0]
 [        3         0]]


In [ ]:
#Initialize an all one array with size 4X2.
import numpy as np
a = np.ones((4,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np
b = np.full((3,3) , 7, dtype = int)
print(b)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
import numpy as np
c= np.array([[1,2,3],
              [5,6,7]])
zero = np.zeros_like(c)
print(zero)

[[0 0 0]
 [0 0 0]]


In [ ]:
#Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
import numpy as np
d =([[3,2,1],
     [6,5,4]])
new = np.ones_like(d)
print(new)

[[1 1 1]
 [1 1 1]]


In [ ]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
import numpy as np
new_list = [1,2,3,4,5]
arr = np.array(new_list)
print(arr)

[1 2 3 4 5]


In [ ]:
#Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np
ar= np.arange(10,50)
print(ar)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Create a 3X3 matrix with values ranging from 0 to 8.
#{Hint:look for np.reshape()}
import numpy as np
m = np.arange(9).reshape(3,3)
print(m)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np
ma= np.eye(3)
print(ma)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Create a random array of size 30 and find the mean of the array.
#{Hint:check for np.random.random() and array.mean() function}
import numpy as np

arr = np.random.randint(1,101,30)
m = arr.mean()

print("Array ", arr)
print("Mean is", m)


Array  [ 9 12 21 64  3 90 73 66 72 25 72 63 41 97 12 39 27 64 10 21 59 80 86 10
 64 27 36 27 13 52]
Mean is 44.5


In [ ]:
#Create a 10X10 array with random values and find the minimum and maximum values.
import numpy as np
arr = np.random.randint(1,101,(10,10))
min_value = arr.min()
max_value = arr.max()
print(arr)
print("minimum value is", min_value)
print("maximum value is", max_value)

[[12 63 74 37 96 31 97  2 11 30]
 [ 4 79 99 23 22 74 60 32 58 72]
 [10 86 67 98 52 46 77 91 41 42]
 [41 52 43 78 39 84 17 53  3  1]
 [11 62 79  1 81 16 13 40  1 41]
 [ 3 31 65 99 15 45 96  1 85 23]
 [65 97 41 25 26 30 81 67  1 49]
 [39 33 11 80 93 81 81 55 41 41]
 [18 51 38 15 89 39 47 31  4 78]
 [39 76 17 68 89 89  8 12 93 26]]
minimum value is 1
maximum value is 99


In [ ]:
#Create a zero array of size 10 and replace 5th element with 1.
import numpy as np
arr = np.zeros(10, dtype=int)
arr[4] = 1
print(arr)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
#Reverse an array arr = [1,2,0,0,4,0].
import numpy as np
a = [1,2,3,4,5]
arr = a[::-1]
print(arr)

[5, 4, 3, 2, 1]


In [ ]:
#Create a 2d array with 1 on border and 0 inside.
import numpy as np
arr = np.ones((5, 5), dtype=int)
arr[1:-1, 1:-1] = 0

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np
a = np.zeros((8, 8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1

print(a)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Add the two array.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
a = x+y
print(a)

[[ 6  8]
 [10 13]]


In [ ]:
#Subtract the two array.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
a = x-y
print(a)

[[-4 -4]
 [-4 -3]]


In [ ]:
#Multiply the array with any integers of your choice.
import numpy as np
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])
x_m = x * 3
y_m = y * 2
v_m = v * 5
w_m = w * 4
print("x multiplied by 3:\n", x_m)
print("\ny multiplied by 2:\n", y_m)
print("\nv multiplied by 5:\n", v_m)
print("\nw multiplied by 4:\n", w_m)


x multiplied by 3:
 [[ 3  6]
 [ 9 15]]

y multiplied by 2:
 [[10 12]
 [14 16]]

v multiplied by 5:
 [45 50]

w multiplied by 4:
 [44 48]


In [ ]:
#Concatenate x(and)y along row and Concatenate v(and)w along column.
#{Hint:try np.concatenate() or np.vstack() functions.
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
xy_row = np.concatenate((x, y), axis=0)
print(xy_row)


[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [2]:
#Prove A.A−1 = I
import numpy as np
A = np.array([[3,4],[7,8]], dtype = int)
B = np.array([[5,3],[2,1]], dtype = int)
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
result_int = np.round(result).astype(int)
print(f"A * A^-1 = \n {result_int}")
print("\n")


A * A^-1 = 
 [[1 0]
 [0 1]]




In [3]:
#Prove AB ̸= BA
import numpy as np
A = np.array([[3,4],[7,8]], dtype = int)
B = np.array([[5,3],[2,1]], dtype = int)
result_ab= np.dot(A, B)
result_ba= np.dot(B, A)

print(f"AB = \n {result_ab}")
print(f"BA = \n {result_ba}")
print("Since the value of AB and BA are different, therefore AB ̸= BA.")
print("\n")


AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Since the value of AB and BA are different, therefore AB ̸= BA.




In [4]:
#Prove (AB)T = BTAT
import numpy as np
A = np.array([[3,4],[7,8]], dtype = int)
B = np.array([[5,3],[2,1]], dtype = int)
AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print("Since (AB)^T and B^TA^T are same therefore (AB)^T = B^TA^T ")
print("\n")

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Since (AB)^T and B^TA^T are same therefore (AB)^T = B^TA^T 




In [5]:
#4.Solve the following system of Linear equation using Inverse Methods.
#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9
import numpy as np
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])
x = np.linalg.solve(A_eq, B_eq).astype(int)
print("This is using only np.linalg only ")
print(x)
print("\n")
#Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
a_inv = np.linalg.inv(A_eq)
x = np.dot(a_inv, B_eq).astype(int)
print("This is using np.linagl.inv function ")
print(x)


This is using only np.linalg only 
[ 2  1 -2]


This is using np.linagl.inv function 
[ 2  1 -2]
